name: Deploy
description: "Deploys"
inputs:
  env:
    required: true
  country:
    required: true
  secret_name:
    required: true
runs:
  using: composite
  steps:
    - id: decrypt
      outputs:
        secret_name: $(gpg --decrypt --quiet --batch --passphrase "${{ secrets.PASSPHRASE }}" --output - <(echo "${{ inputs.secret_name }}" | base64 --decode))
    - run: echo "Deploy ${{ inputs.env }} on ${{ inputs.country }} with ${{ steps.decrypt.outputs.secret_name }}"
      shell: bash
