name: Deploy
description: "Deploys"
inputs:
  env:
    required: true
  country:
    required: true
runs:
  using: composite
  steps:
    - run: echo "Deploy ${{ matrix.env }} on ${{ matrix.country }} with ${{ secrets.NAME }}"
      shell: bash
