name: Deploy
description: "Deploys"
inputs:
  env:
    required: true
  country:
    required: true
  secret_name:
    required: true
runs:
  using: composite
  steps:
    - run: echo "Deploy ${{ inputs.env }} on ${{ inputs.country }} with ${{ inputs.secret_name }}"
      shell: bash
