name: Apply

on:
  issue_comment:
    types: [created, edited]

jobs:
  validate:
    if: ${{ github.event.issue.pull_request && github.actor == 'Dgame' }}
    runs-on: ubuntu-latest
    outputs:
      apply: ${{ contains(steps.set-result.outputs.result, 'apply on dev') || contains(steps.set-result.outputs.result, 'apply on stage') }}
    steps:
      - uses: actions/github-script@v5
        id: set-result
        with:
          script: return context.payload.comment.body.toLowerCase()
          result-encoding: string
  apply:
    needs: validate
    if: ${{ needs.validate.outputs.apply }}
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: '+1'
      - name: Comment Plan
        run: gh pr comment --body "Hello, @${{ github.actor }}! Applying on ${{ steps.regex-match.outputs.group1 }} was good" "$PR_URL"
        env:
          PR_URL: ${{ github.event.issue.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
