# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  composer-validate:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: true
      matrix:
        composer-version: ['v1', 'v2']
        experimental: [false]
        include:
          - composer-version: 'latest'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:${{ matrix.composer-version }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate composer.json
        run: composer validate --strict
  composer:
    if: ${{ always() }}
    runs-on: 'ubuntu-latest'
    needs: composer-validate
    steps:
      - run: exit ${{ needs.composer-validate.result == 'success' }}
  php-lint:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: true
      matrix:
        php-version: ['8.0', '8.1']
        experimental: [false]
        include:
          - composer-version: '8.2'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpstan
      - run: phpstan analyse
  php:
    if: ${{ always() }}
    runs-on: 'ubuntu-latest'
    needs: php-lint
    steps:
      - run: exit ${{ needs.php-lint.result == 'success' }}
