name: Deploy

on:
  pull_request_target:
    types: [ labeled ]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'automerge' && github.actor == 'Dgame' }}
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: wip, work-in-progress
          required-labels: automerge
