on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-eu:
    name: "Deploy on eu"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          env: ${{ inputs.environment }}
          country: eu

  deploy-us:
    name: "Deploy on us"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          env: ${{ inputs.environment }}
          country: us

  deploy-ap:
    name: "Deploy on ap"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          env: ${{ inputs.environment }}
          country: ap
