on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-eu:
    name: "Deploy on eu"
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      secret_name: ${{ secrets.NAME }}
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{secrets.NAME }} | sed 's/./& /g'
      - uses: ./.github/actions/deploy
        with:
          env: ${{ inputs.environment }}
          secret_name: ${{ secrets.NAME }}
          country: eu

  deploy-us:
    needs: deploy-eu
    name: "Deploy on us"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          env: ${{ inputs.environment }}
          secret_name: ${{ needs.deploy-eu.outputs.secret_name }}
          country: us

  deploy-ap:
    needs:
      - deploy-eu
      - deploy-us
    name: "Deploy on ap"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          env: ${{ inputs.environment }}
          secret_name: ${{ needs.deploy-eu.outputs.secret_name }}
          country: ap
