name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  test:
    uses: ./.github/workflows/deploy.yml
    with:
      username: ${{ secrets.USERNAME }}
      environment: production
    secrets: inherit
