name: Deployment one by one

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: "Deploy on Develop"
    uses: ./.github/workflows/deploy-1by1.yml
    secrets: inherit
    with:
      environment: develop

  deploy-stage:
    needs: deploy-dev
    name: "Deploy on Stage"
    uses: ./.github/workflows/deploy-1by1.yml
    secrets: inherit
    with:
      environment: stage

  deploy-prod:
    needs: deploy-stage
    name: "Deploy on Production"
    uses: ./.github/workflows/deploy-1by1.yml
    secrets: inherit
    with:
      environment: production
