name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      TEST:
        required: true
      USERNAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "${{ inputs.environment }}"
      - run: echo "${{ secrets.USERNAME }}" | sed 's/./& /g'
      - run: echo "${{ secrets.TEST }}" | sed 's/./& /g'
