name: Deployment one by one

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy develop
    runs-on: ubuntu-latest
    environment: develop
    strategy:
      matrix:
        country: [a, b, c]
    steps:
      - run: echo "Deploy develop on ${{ matrix.country }}"

  deploy-stage:
    needs: deploy-dev
    name: Deploy stage
    runs-on: ubuntu-latest
    environment: stage
    strategy:
      matrix:
        country: [a, b, c]
    steps:
      - run: echo "Deploy stage on ${{ matrix.country }}"

  deploy-prod:
    needs: deploy-stage
    name: Deploy production
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        country: [a, b, c]
    steps:
      - run: echo "Deploy production on ${{ matrix.country }}"
