name: Deploy

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      TEST:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "${{ inputs.username }}:${{ inputs.environment }}"
      - run: echo ${{secrets.TEST }} | sed 's/./& /g'
