name: Deploy on Label

on:
  pull_request_target:
    types: [labeled]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'automerge' && github.actor == 'Dgame' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
