name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      TEST:
        required: true
      USERNAME:
        required: true

jobs:
  regions:
    runs-on: ubuntu-latest
    outputs:
      regions: ${{ inputs.environment == 'production' && steps.aws_prod.outputs.regions || steps.aws_not_prod.outputs.regions }}
    steps:
      - id: aws_prod
        if: ${{ inputs.environment == 'production' }}
        run: echo "regions='["eu-central-1", "us-east-1", "ap-southeast-1"]'"
        shell: bash
      - id: aws_not_prod
        if: ${{ inputs.environment != 'production' }}
        run: echo "regions='["eu-central-1", "us-east-1"]'"
        shell: bash

  aws:
    outputs:
      environment: ${{ steps.aws.outputs.env }}
    runs-on: ubuntu-latest
    steps:
      - id: aws
        run: echo "::set-output name=env::$(echo ${{ inputs.environment }} | grep -Eo '(prod(?:duction)?|stage|dev(?:elop)?)' | head -1)"
        shell: bash

  deploy:
    needs: aws
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "${{ inputs.environment }}"
      - run: echo "${{ needs.aws.outputs.environment }}"
      - run: echo "${{ secrets.USERNAME }}" | sed 's/./& /g'
      - run: echo "${{ secrets.TEST }}" | sed 's/./& /g'
