name: Deployment one by one

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy develop
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          env: develop
          country: eu
      - uses: ./.github/actions/deploy
        with:
          env: develop
          country: us
      - uses: ./.github/actions/deploy
        with:
          env: develop
          country: ap

  deploy-stage:
    needs: deploy-dev
    name: Deploy Stage
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          env: stage
          country: eu
      - uses: ./.github/actions/deploy
        with:
          env: stage
          country: us
      - uses: ./.github/actions/deploy
        with:
          env: stage
          country: ap

  deploy-prod:
    needs: deploy-stage
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          env: production
          country: eu
      - uses: ./.github/actions/deploy
        with:
          env: production
          country: us
      - uses: ./.github/actions/deploy
        with:
          env: production
          country: ap
