name: Deployment one by one

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy develop
    runs-on: ubuntu-latest
    environment: develop
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        country: [a, b, c]
    steps:
      - uses: ./.github/actions/deploy
        with:
          env: develop
          country: ${{ matrix.country }}

  deploy-stage:
    name: Deploy Stage
    runs-on: ubuntu-latest
    environment: stage
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        country: [a, b, c]
    steps:
      - uses: ./.github/actions/deploy
        with:
          env: stage
          country: ${{ matrix.country }}

  deploy-prod:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: production
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        country: [a, b, c]
    steps:
      - uses: ./.github/actions/deploy
        with:
          env: production
          country: ${{ matrix.country }}
