name: On Delete

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Detect file changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-status ${{ github.event.pull_request.base.sha }} HEAD > changes.txt
          cat changes.txt | grep '\.md$' > changed_md_files.txt
          cat changes.txt | grep '^D' | grep '\.md$' > deleted_md_files.txt
        shell: bash

      - name: Run if there were deletions
        run: test -s deleted_md_files.txt && echo "Deleted Markdown files: $(cat deleted_md_files.txt)" || echo "No deletions"
        id: deletions

      - name: Run if there were changes
        run: test -s changed_md_files.txt && echo "Changed Markdown files: $(cat changed_md_files.txt)" || echo "No changes"
        id: changes

      - name: Build and test
        if: ${{ steps.deletions.outcome == 'success' }}
        run: |
          # Add steps to run your build/test commands here
          echo "Build and test after deletion of Markdown files"

      - name: Run other action
        if: ${{ steps.changes.outcome == 'success' }}
        run: |
          # Add steps to run your other action here
          echo "Other action after change of Markdown files"
