name: On Delete

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Detect file changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-status ${{ github.event.pull_request.base.sha }} HEAD > changes.txt
          cat changes.txt | grep '\.md$' > changed_md_files.txt
          cat changes.txt | grep '^D' | grep '\.md$' > deleted_md_files.txt
        shell: bash

      - name: Run if there were deletions
        if: ${{ fileExists('deleted_md_files.txt') && !isEmpty(github.event.client_payload.deleted_md_files) }}
        run: |
          # Add steps to run your build/test commands here
          echo "Deleted Markdown files: ${{ join(github.event.client_payload.deleted_md_files, ', ') }}"

      - name: Run if there were changes
        if: ${{ fileExists('changed_md_files.txt') && !isEmpty(github.event.client_payload.changed_md_files) }}
        run: |
          # Add steps to run your build/test commands here
          echo "Changed Markdown files: ${{ join(github.event.client_payload.changed_md_files, ', ') }}"
